images:
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: k8s.gcr.io/sig-storage/csi-attacher
  tag: v3.4.0
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: k8s.gcr.io/sig-storage/csi-resizer
  tag: v1.4.0
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  tag: v2.4.0
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: k8s.gcr.io/sig-storage/csi-provisioner
  tag: v2.2.2
  targetVersion: "< 1.20"
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: k8s.gcr.io/sig-storage/csi-provisioner
  tag: v3.1.0
  targetVersion: ">= 1.20"
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/csi-snapshotter
  tag: v3.0.3
  targetVersion: "< 1.20"
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/csi-snapshotter
  tag: v5.0.1
  targetVersion: ">= 1.20"
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-controller
  tag: v3.0.3
  targetVersion: "< 1.20"
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-controller
  tag: v5.0.1
  targetVersion: ">= 1.20"
- name: csi-snapshot-validation-webhook
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-validation-webhook
  tag: "v3.0.3"
  targetVersion: "< 1.20"
- name: csi-snapshot-validation-webhook
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: k8s.gcr.io/sig-storage/snapshot-validation-webhook
  tag: "v5.0.1"
  targetVersion: ">= 1.20"
- name: vsphere-cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-vsphere
  repository: gcr.io/cloud-provider-vsphere/cpi/release/manager
  tag: v1.22.4
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.45.0"
- name: machine-controller-manager-provider-vsphere
  sourceRepository: github.com/gardener/machine-controller-manager-provider-vsphere
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-vsphere
  tag: "v0.15.0"
- name: vsphere-csi-driver-controller
  #sourceRepository: github.com/kubernetes-sigs/vsphere-csi-driver
  #repository: gcr.io/cloud-provider-vsphere/csi/release/driver
  #tag: v2.4.1
  sourceRepository: github.com/gardener/vsphere-csi-driver
  repository: eu.gcr.io/gardener-project/patches/vsphere-csi-driver/driver
  tag: 2.6.0-gardener2
- name: vsphere-csi-driver-node
  #sourceRepository: github.com/kubernetes-sigs/vsphere-csi-driver
  #repository: gcr.io/cloud-provider-vsphere/csi/release/driver
  #tag: v2.4.1
  sourceRepository: github.com/gardener/vsphere-csi-driver
  repository: eu.gcr.io/gardener-project/patches/vsphere-csi-driver/driver
  tag: 2.6.0-gardener2
- name: vsphere-csi-driver-syncer
  #sourceRepository: github.com/kubernetes-sigs/vsphere-csi-driver
  #repository: gcr.io/cloud-provider-vsphere/csi/release/syncer
  #tag: v2.4.1
  sourceRepository: github.com/gardener/vsphere-csi-driver
  repository: eu.gcr.io/gardener-project/patches/vsphere-csi-driver/syncer
  tag: 2.6.0-gardener2
- name: liveness-probe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: k8s.gcr.io/sig-storage/livenessprobe
  tag: v2.7.0
